cass_error: add conversion logic for MetadataError
I tried to map the underlying errors as precisely as possible (as of now).

The most important one is the `MetadataError::ConnectionPoolError`
which should be mapped to `LIB_NO_HOSTS_AVAILABLE`. This is required by the test.